#include "modules.h"
#include "shim_registry.h"

#include <array>

void RegisterLibSystemShims(ShimRegistry& registry) {
    registry.AddZeroData("__DefaultRuneLocale", 64);
    registry.AddZeroData("__NSConcreteGlobalBlock", 64);
    registry.AddZeroData("__NSConcreteStackBlock", 64);
    registry.AddZeroData("_NDR_record", 8);
    registry.AddResolver("___stderrp", [](ShimContext& ctx) {
        return ctx.RegisterStdStreamCell("___stderrp", true);
    });
    registry.AddResolver("___stdoutp", [](ShimContext& ctx) {
        return ctx.RegisterStdStreamCell("___stdoutp", false);
    });
    registry.AddResolver("__dispatch_main_q", [](ShimContext& ctx) {
        return ctx.RegisterDispatchMainQueue("__dispatch_main_q");
    });
    // ___stack_chk_guard: non-zero canary value
    registry.AddResolver("___stack_chk_guard", [](ShimContext& ctx) {
        return ctx.RegisterU32Data("___stack_chk_guard", 0xDEAD1337u);
    });
    // mach_task_self_: fake mach port number
    registry.AddResolver("_mach_task_self_", [](ShimContext& ctx) {
        return ctx.RegisterU32Data("_mach_task_self_", 0x00000103u);
    });
    // vm_page_size
    registry.AddResolver("_vm_page_size", [](ShimContext& ctx) {
        return ctx.RegisterU32Data("_vm_page_size", 4096u);
    });

    static constexpr std::array kFunctions{
        "_free",
        "_malloc",
        "_calloc",
        "_realloc",
        "dyld_stub_binder",
        "_CCCrypt",
        "_CCHmac",
        "_CC_MD5",
        "_CC_SHA1",
        "_CC_SHA1_Final",
        "_CC_SHA1_Init",
        "_CC_SHA1_Update",
        "_CC_SHA256",
        "_OSAtomicAdd32Barrier",
        "_OSAtomicCompareAndSwap32Barrier",
        "_OSAtomicCompareAndSwapPtrBarrier",
        "_OSMemoryBarrier",
        "_OSSpinLockLock",
        "_OSSpinLockUnlock",
        "__Block_object_assign",
        "__Block_object_dispose",
        "__NSGetExecutablePath",
        "___assert_rtn",
        "___cxa_atexit",
        "___error",
        "___maskrune",
        "___snprintf_chk",
        "___sprintf_chk",
        "___strcat_chk",
        "___strcpy_chk",
        "___stack_chk_fail",
        "___tolower",
        "___toupper",
        "__dyld_get_image_header",
        "__dyld_get_image_name",
        "__dyld_get_image_vmaddr_slide",
        "__dyld_image_count",
        "__dyld_register_func_for_add_image",
        "__dyld_register_func_for_remove_image",
        "_abort",
        "_arc4random",
        "_asl_free",
        "_asl_get",
        "_asl_key",
        "_asl_new",
        "_asl_search",
        "_asl_set_query",
        "_aslresponse_free",
        "_aslresponse_next",
        "_atan2",
        "_atexit",
        "_atoi",
        "_backtrace",
        "_backtrace_symbols_fd",
        "_bzero",
        "_ceil",
        "_ceilf",
        "_close",
        "_closedir",
        "_connect",
        "_cos",
        "_cosf",
        "_dispatch_after",
        "_dispatch_async",
        "_dispatch_get_current_queue",
        "_dispatch_get_global_queue",
        "_dispatch_once",
        "_dispatch_queue_create",
        "_dispatch_release",
        "_dispatch_set_target_queue",
        "_dispatch_sync",
        "_dispatch_time",
        "_dladdr",
        "_drand48",
        "_exception_raise",
        "_exception_raise_state",
        "_exception_raise_state_identity",
        "_exit",
        "_exp2",
        "_exp2f",
        "_fclose",
        "_fcntl",
        "_feof",
        "_fflush",
        "_fgets",
        "_fileno",
        "_floor",
        "_floorf",
        "_fmax",
        "_fmaxf",
        "_fmod",
        "_fopen",
        "_fprintf",
        "_fputs",
        "_fread",
        "_freeaddrinfo",
        "_freeifaddrs",
        "_fseek",
        "_fstat",
        "_ftell",
        "_fwrite",
        "_gai_strerror",
        "_getaddrinfo",
        "_gethostname",
        "_getifaddrs",
        "_getnameinfo",
        "_getpid",
        "_getprogname",
        "_getsectdatafromheader",
        "_getsectdatafromheader_64",
        "_gettimeofday",
        "_host_page_size",
        "_host_statistics",
        "_if_nametoindex",
        "_inet_aton",
        "_inet_ntop",
        "_ldexp",
        "_log10",
        "_logf",
        "_longjmp",
        "_mach_absolute_time",
        "_mach_host_self",
        "_mach_make_memory_entry_64",
        "_mach_msg",
        "_mach_port_allocate",
        "_mach_port_deallocate",
        "_mach_port_insert_right",
        "_mach_port_mod_refs",
        "_mach_port_move_member",
        "_mach_port_request_notification",
        "_mach_thread_self",
        "_mach_timebase_info",
        "_memcmp",
        "_memcpy",
        "_memmove",
        "_memset",
        "_memset_pattern16",
        "_mkstemp",
        "_mmap",
        "_munmap",
        "_open",
        "_opendir",
        "_perror",
        "_pow",
        "_powf",
        "_printf",
        "_pthread_attr_destroy",
        "_pthread_attr_init",
        "_pthread_attr_setdetachstate",
        "_pthread_cond_destroy",
        "_pthread_cond_init",
        "_pthread_cond_signal",
        "_pthread_cond_wait",
        "_pthread_create",
        "_pthread_join",
        "_pthread_mach_thread_np",
        "_pthread_mutex_destroy",
        "_pthread_mutex_init",
        "_pthread_mutex_lock",
        "_pthread_mutex_unlock",
        "_putchar",
        "_puts",
        "_qsort",
        "_raise",
        "_rand",
        "_read",
        "_readdir",
        "_recv",
        "_regcomp",
        "_regerror",
        "_regexec",
        "_regfree",
        "_remove",
        "_rename",
        "_round",
        "_roundf",
        "_select$DARWIN_EXTSN",
        "_send",
        "_setjmp",
        "_setsockopt",
        "_setxattr",
        "_sigaction",
        "_sigaltstack",
        "_signal",
        "_sin",
        "_sinf",
        "_snprintf",
        "_socket",
        "_socketpair",
        "_sprintf",
        "_srand",
        "_srand48",
        "_sscanf",
        "_stat",
        "_statfs",
        "_strcasecmp",
        "_strchr",
        "_strcmp",
        "_strcpy",
        "_strcspn",
        "_strdup",
        "_strerror",
        "_strlen",
        "_strncmp",
        "_strncpy",
        "_strnlen",
        "_strstr",
        "_strtod",
        "_strtol",
        "_sysctl",
        "_sysctlbyname",
        "_system",
        "_task_get_exception_ports",
        "_task_info",
        "_task_swap_exception_ports",
        "_task_threads",
        "_thread_get_exception_ports",
        "_thread_get_state",
        "_thread_resume",
        "_thread_suspend",
        "_thread_swap_exception_ports",
        "_time",
        "_uname",
        "_unlink",
        "_usleep",
        "_vfprintf",
        "_vm_allocate",
        "_vm_deallocate",
        "_vm_map",
        "_vm_protect",
        "_vm_read_overwrite",
        "_vprintf",
        "_vsnprintf",
        "_write",
    };
    for (const char* symbol : kFunctions) {
        registry.AddGenericFunction(symbol);
    }
}
